// eslint-disable-next-line no-unused-vars
export const RAW_CHANNELS = [
	{
		id: "C04N64G74CC",
		name: "random",
		is_channel: true,
		is_group: false,
		is_im: false,
		is_mpim: false,
		is_private: false,
		created: 1675563220,
		is_archived: false,
		is_general: false,
		unlinked: 0,
		name_normalized: "random",
		is_shared: false,
		is_org_shared: false,
		is_pending_ext_shared: false,
		pending_shared: [],
		context_team_id: "T04MP4CAQ3H",
		updated: 1736895963242,
		parent_conversation: null,
		creator: "U04NG9G5SD7",
		is_ext_shared: false,
		shared_team_ids: ["T04MP4CAQ3H"],
		pending_connected_team_ids: [],
		is_member: false,
		topic: {
			value: "",
			creator: "",
			last_set: 0,
		},
		purpose: {
			value:
				"This channel is for... well, everything else. It’s a place for team jokes, spur-of-the-moment ideas and funny GIFs. Go wild!",
			creator: "U04NG9G5SD7",
			last_set: 1675563220,
		},
		properties: {
			use_case: "random",
		},
		previous_names: [],
		num_members: 2,
	},
	{
		id: "C04NG9G5Y4R",
		name: "all-behrouzpersonal",
		is_channel: true,
		is_group: false,
		is_im: false,
		is_mpim: false,
		is_private: false,
		created: 1675563219,
		is_archived: false,
		is_general: true,
		unlinked: 0,
		name_normalized: "all-behrouzpersonal",
		is_shared: false,
		is_org_shared: false,
		is_pending_ext_shared: false,
		pending_shared: [],
		context_team_id: "T04MP4CAQ3H",
		updated: 1736895995267,
		parent_conversation: null,
		creator: "U04NG9G5SD7",
		is_ext_shared: false,
		shared_team_ids: ["T04MP4CAQ3H"],
		pending_connected_team_ids: [],
		is_member: false,
		topic: {
			value: "",
			creator: "",
			last_set: 0,
		},
		purpose: {
			value:
				"This is the one channel that will always include everyone. It’s a great spot for announcements and team-wide conversations.",
			creator: "U04NG9G5SD7",
			last_set: 1675563219,
		},
		properties: {
			use_case: "welcome",
		},
		previous_names: ["general"],
		num_members: 2,
	},
	{
		id: "C04NTB3B0QY",
		name: "null",
		is_channel: true,
		is_group: false,
		is_im: false,
		is_mpim: false,
		is_private: false,
		created: 1675563252,
		is_archived: false,
		is_general: false,
		unlinked: 0,
		name_normalized: "null",
		is_shared: false,
		is_org_shared: false,
		is_pending_ext_shared: false,
		pending_shared: [],
		context_team_id: "T04MP4CAQ3H",
		updated: 1736895963562,
		parent_conversation: null,
		creator: "U04NG9G5SD7",
		is_ext_shared: false,
		shared_team_ids: ["T04MP4CAQ3H"],
		pending_connected_team_ids: [],
		is_member: false,
		topic: {
			value: "",
			creator: "",
			last_set: 0,
		},
		purpose: {
			value:
				"This channel is for everything #null. Hold meetings, share docs and make decisions together with your team.",
			creator: "U04NG9G5SD7",
			last_set: 1675563252,
		},
		properties: {
			use_case: "project",
		},
		previous_names: [],
		num_members: 2,
	},
	{
		id: "C088P059D5G",
		name: "general",
		is_channel: true,
		is_group: false,
		is_im: false,
		is_mpim: false,
		is_private: false,
		created: 1736897542,
		is_archived: false,
		is_general: false,
		unlinked: 0,
		name_normalized: "general",
		is_shared: false,
		is_org_shared: false,
		is_pending_ext_shared: false,
		pending_shared: [],
		context_team_id: "T04MP4CAQ3H",
		updated: 1737039364386,
		parent_conversation: null,
		creator: "U04NG9G5SD7",
		is_ext_shared: false,
		shared_team_ids: ["T04MP4CAQ3H"],
		pending_connected_team_ids: [],
		is_member: true,
		topic: {
			value: "",
			creator: "",
			last_set: 0,
		},
		purpose: {
			value: "",
			creator: "",
			last_set: 0,
		},
		properties: {
			tabs: [
				{
					type: "files",
					label: "",
					id: "files",
				},
			],
			tabz: [
				{
					type: "files",
				},
			],
		},
		previous_names: [],
		num_members: 3,
	},
	{
		id: "C088P3YLJN6",
		name: "test-1",
		is_channel: true,
		is_group: false,
		is_im: false,
		is_mpim: false,
		is_private: false,
		created: 1736899840,
		is_archived: false,
		is_general: false,
		unlinked: 0,
		name_normalized: "test-1",
		is_shared: false,
		is_org_shared: false,
		is_pending_ext_shared: false,
		pending_shared: [],
		context_team_id: "T04MP4CAQ3H",
		updated: 1736899840146,
		parent_conversation: null,
		creator: "U04NG9G5SD7",
		is_ext_shared: false,
		shared_team_ids: ["T04MP4CAQ3H"],
		pending_connected_team_ids: [],
		is_member: true,
		topic: {
			value: "",
			creator: "",
			last_set: 0,
		},
		purpose: {
			value: "",
			creator: "",
			last_set: 0,
		},
		previous_names: [],
		num_members: 2,
	},
	{
		id: "C089CNEDG2D",
		name: "my-private-channel",
		is_channel: true,
		is_group: false,
		is_im: false,
		is_mpim: false,
		is_private: true,
		created: 1737048224,
		is_archived: false,
		is_general: false,
		unlinked: 0,
		name_normalized: "my-private-channel",
		is_shared: false,
		is_org_shared: false,
		is_pending_ext_shared: false,
		pending_shared: [],
		context_team_id: "T04MP4CAQ3H",
		updated: 1737048224895,
		parent_conversation: null,
		creator: "U04NG9G5SD7",
		is_ext_shared: false,
		shared_team_ids: ["T04MP4CAQ3H"],
		pending_connected_team_ids: [],
		is_member: true,
		topic: {
			value: "",
			creator: "",
			last_set: 0,
		},
		purpose: {
			value: "",
			creator: "",
			last_set: 0,
		},
		num_members: 2,
	},
];
