// a simple comment to check CIs pass
/* eslint-disable no-unused-vars */
export const USERS = [
	{
		userId: "USLACKBOT",
		title: "",
		name: "slackbot",
		realName: "Slackbot",
		realNameNormalised: "Slackbot",
		displayNameNormalised: "Slackbot",
		firstname: "slackbot",
		lastname: "",
		isAdmin: false,
		isOwner: false,
		isBot: false,
		isAppUser: false,
	},
	{
		userId: "U04NG9G5SD7",
		title: "",
		name: "behrouzkarimi1993",
		realName: "Behrouz Karimi",
		realNameNormalised: "Behrouz Karimi",
		displayNameNormalised: "Karimi",
		firstname: "Behrouz",
		lastname: "Karimi",
		isAdmin: true,
		isOwner: true,
		isBot: false,
		isAppUser: false,
	},
	{
		userId: "U088K50CAP9",
		title: "",
		name: "behrouz1993",
		realName: "BehrouzTwo",
		realNameNormalised: "BehrouzTwo",
		displayNameNormalised: "BehrouzTwo",
		firstname: "BehrouzTwo",
		lastname: "",
		isAdmin: false,
		isOwner: false,
		isBot: false,
		isAppUser: false,
	},
	{
		userId: "U088NRXR8QK",
		title: "",
		name: "slackdashboard",
		realName: "Slack-dashboard",
		realNameNormalised: "Slack-dashboard",
		displayNameNormalised: "",
		firstname: "Slack-dashboard",
		lastname: "",
		isAdmin: false,
		isOwner: false,
		isBot: true,
		isAppUser: false,
	},
];
