/* eslint-disable no-unused-vars */
const listOfUsers = [
	{
		userId: "USLACKBOT",
		title: "",
		name: "slackbot",
		realName: "Slackbot",
		realNameNormalised: "Slackbot",
		displayNameNormalised: "Slackbot",
		firstname: "slackbot",
		lastname: "",
		isAdmin: false,
		isOwner: false,
		isBot: false,
		isAppUser: false,
	},
	{
		userId: "U04NG9G5SD7",
		title: "",
		name: "behrouzkarimi1993",
		realName: "Behrouz Karimi",
		realNameNormalised: "Behrouz Karimi",
		displayNameNormalised: "Karimi",
		firstname: "Behrouz",
		lastname: "Karimi",
		isAdmin: true,
		isOwner: true,
		isBot: false,
		isAppUser: false,
	},
	{
		userId: "U088K50CAP9",
		title: "",
		name: "behrouz1993",
		realName: "BehrouzTwo",
		realNameNormalised: "BehrouzTwo",
		displayNameNormalised: "BehrouzTwo",
		firstname: "BehrouzTwo",
		lastname: "",
		isAdmin: false,
		isOwner: false,
		isBot: false,
		isAppUser: false,
	},
	{
		userId: "U088NRXR8QK",
		title: "",
		name: "slackdashboard",
		realName: "Slack-dashboard",
		realNameNormalised: "Slack-dashboard",
		displayNameNormalised: "",
		firstname: "Slack-dashboard",
		lastname: "",
		isAdmin: false,
		isOwner: false,
		isBot: true,
		isAppUser: false,
	},
];

const messageOfOneChannel = [
	{
		user: "U04NG9G5SD7",
		messageText: "Latest text for test",
		replyCount: 0,
		replyUsersCount: 1,
		replyUsers: ["U04NG9G5SD7"],
		ts: "1737138654.684139",
		reactions: ["U04NG9G5SD7"],
	},
	{
		user: "U088K50CAP9",
		messageText: "<@U088K50CAP9> has joined the channel",
		replyCount: 0,
		replyUsersCount: 0,
		replyUsers: [],
		ts: "1737045001.377839",
		reactions: ["U04NG9G5SD7"],
	},
	{
		user: "U04NG9G5SD7",
		messageText: "4",
		replyCount: 0,
		replyUsersCount: 0,
		replyUsers: [],
		ts: "1736899807.710989",
		reactions: [],
	},
	{
		user: "U04NG9G5SD7",
		messageText: "Hi",
		replyCount: 0,
		replyUsersCount: 1,
		replyUsers: ["U04NG9G5SD7"],
		ts: "1736899785.261429",
		reactions: [],
	},
	{
		user: "U088NRXR8QK",
		messageText: "<@U088NRXR8QK> has joined the channel",
		replyCount: 0,
		replyUsersCount: 0,
		replyUsers: [],
		ts: "1736897774.013529",
		reactions: [],
	},
	{
		user: "U04NG9G5SD7",
		messageText: "<@U04NG9G5SD7> has joined the channel",
		replyCount: 0,
		replyUsersCount: 0,
		replyUsers: [],
		ts: "1736897542.904719",
		reactions: ["U04NG9G5SD7"],
	},
];
