// eslint-disable-next-line no-unused-vars
const getAllChannelsFuncReturn = [
	{
		channelId: "C04N64G74CC",
		channelName: "random",
		isChannel: true,
		isGroup: false,
		isPrivate: false,
		creationDateTime: 1675563220,
		numOfMembers: 2,
	},
	{
		channelId: "C04NG9G5Y4R",
		channelName: "all-behrouzpersonal",
		isChannel: true,
		isGroup: false,
		isPrivate: false,
		creationDateTime: 1675563219,
		numOfMembers: 2,
	},
	{
		channelId: "C04NTB3B0QY",
		channelName: "null",
		isChannel: true,
		isGroup: false,
		isPrivate: false,
		creationDateTime: 1675563252,
		numOfMembers: 2,
	},
	{
		channelId: "C088P059D5G",
		channelName: "general",
		isChannel: true,
		isGroup: false,
		isPrivate: false,
		creationDateTime: 1736897542,
		numOfMembers: 3,
	},
	{
		channelId: "C088P3YLJN6",
		channelName: "test-1",
		isChannel: true,
		isGroup: false,
		isPrivate: false,
		creationDateTime: 1736899840,
		numOfMembers: 2,
	},
	{
		channelId: "C089CNEDG2D",
		channelName: "my-private-channel",
		isChannel: true,
		isGroup: false,
		isPrivate: true,
		creationDateTime: 1737048224,
		numOfMembers: 2,
	},
];
